// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: DisplayArariboia_V2

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void AvisoPiscando_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Motor;
lv_obj_t * ui_RPM_L;
void ui_event_RPM_L_ARC(lv_event_t * e);
lv_obj_t * ui_RPM_L_ARC;
lv_obj_t * ui_Arc1_Label_Container;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Haste_RPM_L;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_RPM_L_text;
lv_obj_t * ui_RPM_R;
lv_obj_t * ui_RPM_R_ARC;
lv_obj_t * ui_Arc1_Label_Container1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Haste_RPM_R;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_RPM_R_text;
lv_obj_t * ui_RPM_Current_Chart;
lv_obj_t * ui_RPM_L_Current_text;
lv_obj_t * ui_RPM_R_Current_text;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Motor_Warning_img;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Battery_Chart;
lv_obj_t * ui_Battery_Volts_text;
lv_obj_t * ui_Battery_Current_text;
lv_obj_t * ui_Solar_Chart;
lv_obj_t * ui_MPPT_Current_text;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Image2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_arariboialogo[1] = {&ui_img_arariboialogo2_png};
const lv_img_dsc_t * ui_imgset_warningsignal[1] = {&ui_img_warningsignal2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void AvisoPiscando_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 700);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_RPM_L_ARC(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_RPM_L_text, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
