// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: DisplayArariboia_V2

#ifndef _DISPLAYARARIBOIA_V2_UI_H
#define _DISPLAYARARIBOIA_V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void AvisoPiscando_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Motor;
extern lv_obj_t * ui_RPM_L;
void ui_event_RPM_L_ARC(lv_event_t * e);
extern lv_obj_t * ui_RPM_L_ARC;
extern lv_obj_t * ui_Arc1_Label_Container;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Haste_RPM_L;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_RPM_L_text;
extern lv_obj_t * ui_RPM_R;
extern lv_obj_t * ui_RPM_R_ARC;
extern lv_obj_t * ui_Arc1_Label_Container1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Haste_RPM_R;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_RPM_R_text;
extern lv_obj_t * ui_RPM_Current_Chart;
extern lv_obj_t * ui_RPM_L_Current_text;
extern lv_obj_t * ui_RPM_R_Current_text;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Motor_Warning_img;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Battery_Chart;
extern lv_obj_t * ui_Battery_Volts_text;
extern lv_obj_t * ui_Battery_Current_text;
extern lv_obj_t * ui_Solar_Chart;
extern lv_obj_t * ui_MPPT_Current_text;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_gradiente_png);    // assets/Gradiente.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_warningsignal2_png);    // assets/warningSignal2.png
LV_IMG_DECLARE(ui_img_arariboialogo2_png);    // assets/ArariboiaLogo2.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
