// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: DisplayArariboia_V2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x081B47), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Motor, 155);
    lv_obj_set_height(ui_Motor, 238);
    lv_obj_set_align(ui_Motor, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_Motor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPM_L = lv_obj_create(ui_Motor);
    lv_obj_remove_style_all(ui_RPM_L);
    lv_obj_set_width(ui_RPM_L, 139);
    lv_obj_set_height(ui_RPM_L, 86);
    lv_obj_set_x(ui_RPM_L, 0);
    lv_obj_set_y(ui_RPM_L, -75);
    lv_obj_set_align(ui_RPM_L, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPM_L, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPM_L_ARC = lv_arc_create(ui_RPM_L);
    lv_obj_set_width(ui_RPM_L_ARC, 93);
    lv_obj_set_height(ui_RPM_L_ARC, 103);
    lv_obj_set_x(ui_RPM_L_ARC, 0);
    lv_obj_set_y(ui_RPM_L_ARC, 30);
    lv_obj_set_align(ui_RPM_L_ARC, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RPM_L_ARC, 0, 5500);
    lv_arc_set_value(ui_RPM_L_ARC, 3500);
    lv_arc_set_bg_angles(ui_RPM_L_ARC, 210, 330);
    lv_obj_set_style_clip_corner(ui_RPM_L_ARC, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RPM_L_ARC, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPM_L_ARC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RPM_L_ARC, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RPM_L_ARC, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_RPM_L_ARC, lv_color_hex(0xFF5500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPM_L_ARC, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RPM_L_ARC, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RPM_L_ARC, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_RPM_L_ARC, &ui_img_gradiente_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPM_L_ARC, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM_L_ARC, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_L_ARC, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc1_Label_Container = lv_obj_create(ui_RPM_L);
    lv_obj_remove_style_all(ui_Arc1_Label_Container);
    lv_obj_set_width(ui_Arc1_Label_Container, 152);
    lv_obj_set_height(ui_Arc1_Label_Container, 111);
    lv_obj_set_x(ui_Arc1_Label_Container, 0);
    lv_obj_set_y(ui_Arc1_Label_Container, 10);
    lv_obj_set_align(ui_Arc1_Label_Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1_Label_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Arc1_Label_Container);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 33);
    lv_obj_set_y(ui_Label2, 2);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "0");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Arc1_Label_Container);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 12);
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "2750");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Arc1_Label_Container);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -12);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label3, "5500");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Haste_RPM_L = lv_img_create(ui_RPM_L);
    lv_img_set_src(ui_Haste_RPM_L, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_Haste_RPM_L, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Haste_RPM_L, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_Haste_RPM_L, 0);
    lv_obj_set_y(ui_Haste_RPM_L, -20);
    lv_obj_set_align(ui_Haste_RPM_L, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Haste_RPM_L, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Haste_RPM_L, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Haste_RPM_L, 15, 95);
    lv_img_set_angle(ui_Haste_RPM_L, -600);
    lv_img_set_zoom(ui_Haste_RPM_L, 128);

    ui_Panel1 = lv_obj_create(ui_RPM_L);
    lv_obj_set_width(ui_Panel1, 32);
    lv_obj_set_height(ui_Panel1, 32);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 25);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x071845), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_L_text = lv_label_create(ui_RPM_L);
    lv_obj_set_width(ui_RPM_L_text, 34);
    lv_obj_set_height(ui_RPM_L_text, 14);
    lv_obj_set_x(ui_RPM_L_text, 0);
    lv_obj_set_y(ui_RPM_L_text, -10);
    lv_obj_set_align(ui_RPM_L_text, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_RPM_L_text, "5500");
    lv_obj_set_style_text_color(ui_RPM_L_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM_L_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RPM_L_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_L_text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RPM_L_text, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM_L_text, lv_color_hex(0x031543), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_L_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_R = lv_obj_create(ui_Motor);
    lv_obj_remove_style_all(ui_RPM_R);
    lv_obj_set_width(ui_RPM_R, 139);
    lv_obj_set_height(ui_RPM_R, 86);
    lv_obj_set_x(ui_RPM_R, 0);
    lv_obj_set_y(ui_RPM_R, 2);
    lv_obj_set_align(ui_RPM_R, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RPM_R, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RPM_R_ARC = lv_arc_create(ui_RPM_R);
    lv_obj_set_width(ui_RPM_R_ARC, 93);
    lv_obj_set_height(ui_RPM_R_ARC, 103);
    lv_obj_set_x(ui_RPM_R_ARC, 0);
    lv_obj_set_y(ui_RPM_R_ARC, 30);
    lv_obj_set_align(ui_RPM_R_ARC, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_RPM_R_ARC, 0, 5500);
    lv_arc_set_value(ui_RPM_R_ARC, 5000);
    lv_arc_set_bg_angles(ui_RPM_R_ARC, 210, 330);
    lv_obj_set_style_clip_corner(ui_RPM_R_ARC, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RPM_R_ARC, lv_color_hex(0xDEDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPM_R_ARC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RPM_R_ARC, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RPM_R_ARC, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_RPM_R_ARC, &ui_img_gradiente_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_RPM_R_ARC, lv_color_hex(0xFF5500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_RPM_R_ARC, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_RPM_R_ARC, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_RPM_R_ARC, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_RPM_R_ARC, &ui_img_gradiente_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPM_R_ARC, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM_R_ARC, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_R_ARC, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Arc1_Label_Container1 = lv_obj_create(ui_RPM_R);
    lv_obj_remove_style_all(ui_Arc1_Label_Container1);
    lv_obj_set_width(ui_Arc1_Label_Container1, 152);
    lv_obj_set_height(ui_Arc1_Label_Container1, 111);
    lv_obj_set_x(ui_Arc1_Label_Container1, 0);
    lv_obj_set_y(ui_Arc1_Label_Container1, 10);
    lv_obj_set_align(ui_Arc1_Label_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1_Label_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Arc1_Label_Container1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 33);
    lv_obj_set_y(ui_Label5, 2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "0");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Arc1_Label_Container1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 12);
    lv_obj_set_align(ui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label6, "2750");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Arc1_Label_Container1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -12);
    lv_obj_set_y(ui_Label7, 2);
    lv_obj_set_align(ui_Label7, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Label7, "5500");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Haste_RPM_R = lv_img_create(ui_RPM_R);
    lv_img_set_src(ui_Haste_RPM_R, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_Haste_RPM_R, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Haste_RPM_R, LV_SIZE_CONTENT);    /// 180
    lv_obj_set_x(ui_Haste_RPM_R, 0);
    lv_obj_set_y(ui_Haste_RPM_R, -20);
    lv_obj_set_align(ui_Haste_RPM_R, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Haste_RPM_R, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Haste_RPM_R, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_Haste_RPM_R, 15, 95);
    lv_img_set_angle(ui_Haste_RPM_R, 600);
    lv_img_set_zoom(ui_Haste_RPM_R, 128);

    ui_Panel3 = lv_obj_create(ui_RPM_R);
    lv_obj_set_width(ui_Panel3, 32);
    lv_obj_set_height(ui_Panel3, 32);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 25);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xF85F12), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_R_text = lv_label_create(ui_RPM_R);
    lv_obj_set_width(ui_RPM_R_text, 34);
    lv_obj_set_height(ui_RPM_R_text, 14);
    lv_obj_set_x(ui_RPM_R_text, 0);
    lv_obj_set_y(ui_RPM_R_text, -10);
    lv_obj_set_align(ui_RPM_R_text, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_RPM_R_text, "5500");
    lv_obj_set_style_text_color(ui_RPM_R_text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM_R_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RPM_R_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_R_text, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_RPM_R_text, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPM_R_text, lv_color_hex(0xFF5D10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_R_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_Current_Chart = lv_chart_create(ui_Motor);
    lv_obj_set_width(ui_RPM_Current_Chart, 133);
    lv_obj_set_height(ui_RPM_Current_Chart, 65);
    lv_obj_set_x(ui_RPM_Current_Chart, -9);
    lv_obj_set_y(ui_RPM_Current_Chart, 7);
    lv_obj_set_align(ui_RPM_Current_Chart, LV_ALIGN_BOTTOM_MID);
    lv_chart_set_type(ui_RPM_Current_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_RPM_Current_Chart, 25);
    lv_chart_set_range(ui_RPM_Current_Chart, LV_CHART_AXIS_PRIMARY_Y, 0, 60);
    lv_chart_set_range(ui_RPM_Current_Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 60);
    lv_chart_set_axis_tick(ui_RPM_Current_Chart, LV_CHART_AXIS_PRIMARY_X, 4, 2, 5, 2, true, 2);
    lv_chart_set_axis_tick(ui_RPM_Current_Chart, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_RPM_Current_Chart, LV_CHART_AXIS_SECONDARY_Y, 4, 2, 5, 2, true, 50);
    lv_obj_set_style_bg_color(ui_RPM_Current_Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_Current_Chart, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_RPM_Current_Chart, lv_color_hex(0xE6E3E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_RPM_Current_Chart, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RPM_Current_Chart, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RPM_Current_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RPM_Current_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RPM_Current_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_RPM_Current_Chart, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_RPM_Current_Chart, false, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_RPM_Current_Chart, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPM_Current_Chart, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_RPM_Current_Chart, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_decor(ui_RPM_Current_Chart, LV_TEXT_DECOR_NONE, LV_PART_TICKS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_Current_Chart, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_RPM_L_Current_text = lv_label_create(ui_Motor);
    lv_obj_set_width(ui_RPM_L_Current_text, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_RPM_L_Current_text, LV_SIZE_CONTENT);    /// 10
    lv_obj_set_x(ui_RPM_L_Current_text, -62);
    lv_obj_set_y(ui_RPM_L_Current_text, 68);
    lv_obj_set_align(ui_RPM_L_Current_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM_L_Current_text, "60");
    lv_obj_set_style_text_color(ui_RPM_L_Current_text, lv_color_hex(0x001841), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM_L_Current_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_L_Current_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM_R_Current_text = lv_label_create(ui_Motor);
    lv_obj_set_width(ui_RPM_R_Current_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPM_R_Current_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPM_R_Current_text, -62);
    lv_obj_set_y(ui_RPM_R_Current_text, 90);
    lv_obj_set_align(ui_RPM_R_Current_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPM_R_Current_text, "60");
    lv_obj_set_style_text_color(ui_RPM_R_Current_text, lv_color_hex(0xFF5D10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPM_R_Current_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPM_R_Current_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Motor);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -2);
    lv_obj_set_y(ui_Label11, 52);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Corrente Motores");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor_Warning_img = lv_img_create(ui_Motor);
    lv_img_set_src(ui_Motor_Warning_img, &ui_img_warningsignal2_png);
    lv_obj_set_width(ui_Motor_Warning_img, LV_SIZE_CONTENT);   /// 612
    lv_obj_set_height(ui_Motor_Warning_img, LV_SIZE_CONTENT);    /// 612
    lv_obj_set_x(ui_Motor_Warning_img, -10);
    lv_obj_set_y(ui_Motor_Warning_img, -35);
    lv_obj_set_align(ui_Motor_Warning_img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Motor_Warning_img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Motor_Warning_img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 162);
    lv_obj_set_height(ui_Panel2, 238);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Battery_Chart = lv_chart_create(ui_Panel2);
    lv_obj_set_width(ui_Battery_Chart, 119);
    lv_obj_set_height(ui_Battery_Chart, 99);
    lv_obj_set_x(ui_Battery_Chart, 0);
    lv_obj_set_y(ui_Battery_Chart, -56);
    lv_obj_set_align(ui_Battery_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Battery_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Battery_Chart, 25);
    lv_chart_set_range(ui_Battery_Chart, LV_CHART_AXIS_PRIMARY_Y, -20, 60);
    lv_chart_set_range(ui_Battery_Chart, LV_CHART_AXIS_SECONDARY_Y, 48, 54);
    lv_chart_set_axis_tick(ui_Battery_Chart, LV_CHART_AXIS_PRIMARY_X, 4, 2, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Battery_Chart, LV_CHART_AXIS_PRIMARY_Y, 4, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Battery_Chart, LV_CHART_AXIS_SECONDARY_Y, 4, 2, 5, 2, true, 25);
    lv_obj_set_style_bg_color(ui_Battery_Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery_Chart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Battery_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Battery_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Battery_Chart, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Battery_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Battery_Chart, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Battery_Chart, false, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Battery_Chart, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Battery_Chart, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_Battery_Volts_text = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Battery_Volts_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Volts_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Volts_text, 33);
    lv_obj_set_y(ui_Battery_Volts_text, 0);
    lv_obj_set_align(ui_Battery_Volts_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Battery_Volts_text, "54 V");
    lv_obj_set_style_text_color(ui_Battery_Volts_text, lv_color_hex(0xDB3939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Battery_Volts_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Battery_Volts_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery_Current_text = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Battery_Current_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery_Current_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Battery_Current_text, -33);
    lv_obj_set_y(ui_Battery_Current_text, 0);
    lv_obj_set_align(ui_Battery_Current_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Battery_Current_text, "60 A");
    lv_obj_set_style_text_color(ui_Battery_Current_text, lv_color_hex(0x30DD3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Battery_Current_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Battery_Current_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Solar_Chart = lv_chart_create(ui_Panel2);
    lv_obj_set_width(ui_Solar_Chart, 139);
    lv_obj_set_height(ui_Solar_Chart, 95);
    lv_obj_set_x(ui_Solar_Chart, -11);
    lv_obj_set_y(ui_Solar_Chart, 61);
    lv_obj_set_align(ui_Solar_Chart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Solar_Chart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Solar_Chart, 25);
    lv_chart_set_range(ui_Solar_Chart, LV_CHART_AXIS_PRIMARY_Y, 0, 40);
    lv_chart_set_range(ui_Solar_Chart, LV_CHART_AXIS_SECONDARY_Y, 0, 40);
    lv_chart_set_axis_tick(ui_Solar_Chart, LV_CHART_AXIS_PRIMARY_X, 4, 2, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Solar_Chart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Solar_Chart, LV_CHART_AXIS_SECONDARY_Y, 4, 2, 5, 2, true, 25);
    lv_obj_set_style_bg_color(ui_Solar_Chart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Solar_Chart, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Solar_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Solar_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Solar_Chart, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Solar_Chart, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_width(ui_Solar_Chart, 1, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Solar_Chart, false, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_size(ui_Solar_Chart, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Solar_Chart, &lv_font_montserrat_8, LV_PART_TICKS | LV_STATE_DEFAULT);

    ui_MPPT_Current_text = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_MPPT_Current_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPPT_Current_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPPT_Current_text, -53);
    lv_obj_set_y(ui_MPPT_Current_text, 119);
    lv_obj_set_align(ui_MPPT_Current_text, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_MPPT_Current_text, "40 A");
    lv_obj_set_style_text_color(ui_MPPT_Current_text, lv_color_hex(0xE1C027), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPPT_Current_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPPT_Current_text, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, -14);
    lv_obj_set_align(ui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label10, "Bateria");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -13);
    lv_obj_set_y(ui_Label9, 6);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Corrente MPPT");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image2, &ui_img_arariboialogo2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_Image2, -4);
    lv_obj_set_y(ui_Image2, -110);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_RPM_L_ARC, ui_event_RPM_L_ARC, LV_EVENT_ALL, NULL);

}
